services:
    cleverage_process.manager.process:
        class: CleverAge\ProcessBundle\Manager\ProcessManager
        arguments:
            - '@service_container'
            - '@logger'
            - '@doctrine.orm.default_entity_manager'
            - '@cleverage_process.registry.process_configuration'
            - '@cleverage_process.context.contextual_option_resolver'

    cleverage_process.context.contextual_option_resolver:
        class: CleverAge\ProcessBundle\Context\ContextualOptionResolver
