services:
    CleverAge\ProcessBundle\Task\DummyTask:
        shared: false

    CleverAge\ProcessBundle\Task\ConstantOutputTask:
        shared: false

    CleverAge\ProcessBundle\Task\ConstantIterableOutputTask:
        shared: false

    CleverAge\ProcessBundle\Task\DebugTask:
        shared: false

    CleverAge\ProcessBundle\Task\ValidatorTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\NormalizerTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\DenormalizerTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\PropertySetterTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\CsvReaderTask:
        shared: false

    CleverAge\ProcessBundle\Task\CsvWriterTask:
        shared: false

    CleverAge\ProcessBundle\Task\DatabaseReaderTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\DoctrineReaderTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\DoctrineWriterTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\DoctrineDetacherTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\DoctrineRemoverTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\StatCounterTask:
        shared: false

    CleverAge\ProcessBundle\Task\TransformerTask:
        autowire: true
        shared: false

    CleverAge\ProcessBundle\Task\ProcessLauncherTask:
        shared: false
        autowire: true

    CleverAge\ProcessBundle\Task\FolderBrowserTask:
        shared: false

    CleverAge\ProcessBundle\Task\FileRemoverTask:
        shared: false

    CleverAge\ProcessBundle\Task\FileMoverTask:
        shared: false

    CleverAge\ProcessBundle\Task\AggregateIterableTask:
        shared: false

    CleverAge\ProcessBundle\Task\FilterTask:
        shared: false

    CleverAge\ProcessBundle\Task\EventDispatcherTask:
        shared: false
        arguments:
            - '@event_dispatcher'

    CleverAge\ProcessBundle\Task\InputAggregatorTask:
        shared: false
