services:
    CleverAge\ProcessBundle\Transformer\:
        resource: '../../../Transformer/*'
        autowire: true
        public: false
        tags:
            - { name: cleverage.transformer }
            - { name: monolog.logger, channel: cleverage_process_transformer }

    CleverAge\ProcessBundle\Transformer\Cache\:
        resource: '../../../Transformer/Cache\*'
        arguments:
            $cache: '@cache.app'
