services:
    cleverage_process.transformer.mapping:
        class: CleverAge\ProcessBundle\Transformer\MappingTransformer
        arguments:
            - '@property_accessor'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.slugify:
        class: CleverAge\ProcessBundle\Transformer\SlugifyTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.explode:
        class: CleverAge\ProcessBundle\Transformer\ExplodeTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.implode:
        class: CleverAge\ProcessBundle\Transformer\ImplodeTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.trim:
        class: CleverAge\ProcessBundle\Transformer\TrimTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.sprintf:
        class: CleverAge\ProcessBundle\Transformer\SprintfTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.array_map:
        class: CleverAge\ProcessBundle\Transformer\ArrayMapTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.array_first:
        class: CleverAge\ProcessBundle\Transformer\ArrayFirstTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.property_accessor:
        class: CleverAge\ProcessBundle\Transformer\PropertyAccessorTransformer
        arguments:
            - '@property_accessor'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.denormalize:
        class: CleverAge\ProcessBundle\Transformer\DenormalizeTransformer
        arguments:
            - '@serializer'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.normalize:
        class: CleverAge\ProcessBundle\Transformer\NormalizeTransformer
        arguments:
            - '@serializer'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.convert_value:
        class: CleverAge\ProcessBundle\Transformer\ConvertValueTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.callback:
        class: CleverAge\ProcessBundle\Transformer\CallbackTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.wrapper:
        class: CleverAge\ProcessBundle\Transformer\WrapperTransformer
        arguments:
            - '@property_accessor'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.evaluator:
        class: CleverAge\ProcessBundle\Transformer\EvaluatorTransformer
        tags:
            - { name: cleverage.transformer }
