services:
    CleverAge\ProcessBundle\Transformer\MappingTransformer:
        public: false
        autowire: true
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\SlugifyTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\ExplodeTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\ImplodeTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\TrimTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\SprintfTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\ArrayMapTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\ArrayFirstTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\PropertyAccessorTransformer:
        public: false
        autowire: true
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\DenormalizeTransformer:
        public: false
        autowire: true
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\NormalizeTransformer:
        public: false
        autowire: true
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\ConvertValueTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\CallbackTransformer:
        public: false
        tags:
            - { name: cleverage.transformer }

    CleverAge\ProcessBundle\Transformer\WrapperTransformer:
        public: false
        autowire: true
        tags:
            - { name: cleverage.transformer }
