services:
    cleverage_process.transformer.mapping:
        class: CleverAge\ProcessBundle\Transformer\MappingTransformer
        arguments:
            - '@property_accessor'
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.slugify:
        class: CleverAge\ProcessBundle\Transformer\SlugifyTransformer
        tags:
            - { name: cleverage.transformer }

    cleverage_process.transformer.explode:
        class: CleverAge\ProcessBundle\Transformer\ExplodeTransformer
        tags:
            - { name: cleverage.transformer }
