services:
    CleverAge\ProcessBundle\Addon\Rest\Task\:
        resource: '../../../Addon/Rest/Task/*'
        autowire: true
        public: true
        shared: false
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }
