services:
    CleverAge\ProcessBundle\Addon\Flysystem\Task\:
        resource: '../../../Addon/Flysystem/Task/*'
        autowire: true
        public: true
        shared: false
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }
